# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uiuc_incas_server.models.base_model_ import Model
from uiuc_incas_server.models.actor_to_actor_edge import ActorToActorEdge  # noqa: F401,E501
from uiuc_incas_server.models.base_graph import BaseGraph  # noqa: F401,E501
from uiuc_incas_server import util


class ActorActorGraph(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, graph_id: str=None, provider_name: str=None, graph_name: str=None, distance_name: str=None, version: str=None, time_stamp: str=None, platform: str=None, graph_type: str=None, enrichment_name: str=None, edges: List[ActorToActorEdge]=None):  # noqa: E501
        """ActorActorGraph - a model defined in Swagger

        :param graph_id: The graph_id of this ActorActorGraph.  # noqa: E501
        :type graph_id: str
        :param provider_name: The provider_name of this ActorActorGraph.  # noqa: E501
        :type provider_name: str
        :param graph_name: The graph_name of this ActorActorGraph.  # noqa: E501
        :type graph_name: str
        :param distance_name: The distance_name of this ActorActorGraph.  # noqa: E501
        :type distance_name: str
        :param version: The version of this ActorActorGraph.  # noqa: E501
        :type version: str
        :param time_stamp: The time_stamp of this ActorActorGraph.  # noqa: E501
        :type time_stamp: str
        :param platform: The platform of this ActorActorGraph.  # noqa: E501
        :type platform: str
        :param graph_type: The graph_type of this ActorActorGraph.  # noqa: E501
        :type graph_type: str
        :param enrichment_name: The enrichment_name of this ActorActorGraph.  # noqa: E501
        :type enrichment_name: str
        :param edges: The edges of this ActorActorGraph.  # noqa: E501
        :type edges: List[ActorToActorEdge]
        """
        self.swagger_types = {
            'graph_id': str,
            'provider_name': str,
            'graph_name': str,
            'distance_name': str,
            'version': str,
            'time_stamp': str,
            'platform': str,
            'graph_type': str,
            'enrichment_name': str,
            'edges': List[ActorToActorEdge]
        }

        self.attribute_map = {
            'graph_id': 'graphId',
            'provider_name': 'providerName',
            'graph_name': 'graphName',
            'distance_name': 'distanceName',
            'version': 'version',
            'time_stamp': 'timeStamp',
            'platform': 'platform',
            'graph_type': 'graphType',
            'enrichment_name': 'enrichmentName',
            'edges': 'edges'
        }
        self._graph_id = graph_id
        self._provider_name = provider_name
        self._graph_name = graph_name
        self._distance_name = distance_name
        self._version = version
        self._time_stamp = time_stamp
        self._platform = platform
        self._graph_type = graph_type
        self._enrichment_name = enrichment_name
        self._edges = edges

    @classmethod
    def from_dict(cls, dikt) -> 'ActorActorGraph':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ActorActorGraph of this ActorActorGraph.  # noqa: E501
        :rtype: ActorActorGraph
        """
        return util.deserialize_model(dikt, cls)

    @property
    def graph_id(self) -> str:
        """Gets the graph_id of this ActorActorGraph.

        This is the unique ID associated to the graph instance.  # noqa: E501

        :return: The graph_id of this ActorActorGraph.
        :rtype: str
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id: str):
        """Sets the graph_id of this ActorActorGraph.

        This is the unique ID associated to the graph instance.  # noqa: E501

        :param graph_id: The graph_id of this ActorActorGraph.
        :type graph_id: str
        """

        self._graph_id = graph_id

    @property
    def provider_name(self) -> str:
        """Gets the provider_name of this ActorActorGraph.

        The team who builds this graph.  # noqa: E501

        :return: The provider_name of this ActorActorGraph.
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name: str):
        """Sets the provider_name of this ActorActorGraph.

        The team who builds this graph.  # noqa: E501

        :param provider_name: The provider_name of this ActorActorGraph.
        :type provider_name: str
        """

        self._provider_name = provider_name

    @property
    def graph_name(self) -> str:
        """Gets the graph_name of this ActorActorGraph.

        The name assigned to the algorithm/method used to construct the graph.  # noqa: E501

        :return: The graph_name of this ActorActorGraph.
        :rtype: str
        """
        return self._graph_name

    @graph_name.setter
    def graph_name(self, graph_name: str):
        """Sets the graph_name of this ActorActorGraph.

        The name assigned to the algorithm/method used to construct the graph.  # noqa: E501

        :param graph_name: The graph_name of this ActorActorGraph.
        :type graph_name: str
        """

        self._graph_name = graph_name

    @property
    def distance_name(self) -> str:
        """Gets the distance_name of this ActorActorGraph.

        The distance function used to build the graph.  # noqa: E501

        :return: The distance_name of this ActorActorGraph.
        :rtype: str
        """
        return self._distance_name

    @distance_name.setter
    def distance_name(self, distance_name: str):
        """Sets the distance_name of this ActorActorGraph.

        The distance function used to build the graph.  # noqa: E501

        :param distance_name: The distance_name of this ActorActorGraph.
        :type distance_name: str
        """

        self._distance_name = distance_name

    @property
    def version(self) -> str:
        """Gets the version of this ActorActorGraph.

        The version ID within the same (providerName, graphName, distanceName)  # noqa: E501

        :return: The version of this ActorActorGraph.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this ActorActorGraph.

        The version ID within the same (providerName, graphName, distanceName)  # noqa: E501

        :param version: The version of this ActorActorGraph.
        :type version: str
        """

        self._version = version

    @property
    def time_stamp(self) -> str:
        """Gets the time_stamp of this ActorActorGraph.

        Used for distinguishing the dynamic graph on time dimension.  # noqa: E501

        :return: The time_stamp of this ActorActorGraph.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: str):
        """Sets the time_stamp of this ActorActorGraph.

        Used for distinguishing the dynamic graph on time dimension.  # noqa: E501

        :param time_stamp: The time_stamp of this ActorActorGraph.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp

    @property
    def platform(self) -> str:
        """Gets the platform of this ActorActorGraph.


        :return: The platform of this ActorActorGraph.
        :rtype: str
        """
        return self._platform

    @platform.setter
    def platform(self, platform: str):
        """Sets the platform of this ActorActorGraph.


        :param platform: The platform of this ActorActorGraph.
        :type platform: str
        """
        allowed_values = ["MEDIA_UNSPECIFIED", "News", "Reddit", "Twitter", "Webpage"]  # noqa: E501
        if platform not in allowed_values:
            raise ValueError(
                "Invalid value for `platform` ({0}), must be one of {1}"
                .format(platform, allowed_values)
            )

        self._platform = platform

    @property
    def graph_type(self) -> str:
        """Gets the graph_type of this ActorActorGraph.

        For discriminator  # noqa: E501

        :return: The graph_type of this ActorActorGraph.
        :rtype: str
        """
        return self._graph_type

    @graph_type.setter
    def graph_type(self, graph_type: str):
        """Sets the graph_type of this ActorActorGraph.

        For discriminator  # noqa: E501

        :param graph_type: The graph_type of this ActorActorGraph.
        :type graph_type: str
        """
        allowed_values = ["MessageMessageGraph", "ActorActorGraph", "ActorMessageGraph"]  # noqa: E501
        if graph_type not in allowed_values:
            raise ValueError(
                "Invalid value for `graph_type` ({0}), must be one of {1}"
                .format(graph_type, allowed_values)
            )

        self._graph_type = graph_type

    @property
    def enrichment_name(self) -> str:
        """Gets the enrichment_name of this ActorActorGraph.

        The type of enrichment used to construct the msg2msg graph.  # noqa: E501

        :return: The enrichment_name of this ActorActorGraph.
        :rtype: str
        """
        return self._enrichment_name

    @enrichment_name.setter
    def enrichment_name(self, enrichment_name: str):
        """Sets the enrichment_name of this ActorActorGraph.

        The type of enrichment used to construct the msg2msg graph.  # noqa: E501

        :param enrichment_name: The enrichment_name of this ActorActorGraph.
        :type enrichment_name: str
        """

        self._enrichment_name = enrichment_name

    @property
    def edges(self) -> List[ActorToActorEdge]:
        """Gets the edges of this ActorActorGraph.


        :return: The edges of this ActorActorGraph.
        :rtype: List[ActorToActorEdge]
        """
        return self._edges

    @edges.setter
    def edges(self, edges: List[ActorToActorEdge]):
        """Sets the edges of this ActorActorGraph.


        :param edges: The edges of this ActorActorGraph.
        :type edges: List[ActorToActorEdge]
        """

        self._edges = edges
