# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uiuc_incas_server.models.base_model_ import Model
from uiuc_incas_server import util


class BaseEdge(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, edge_id: str=None, time_stamp: str=None, provider_name: str=None, enrichment_name: str=None, distance_name: str=None, version: str=None, distance: float=None, edge_type: str=None):  # noqa: E501
        """BaseEdge - a model defined in Swagger

        :param edge_id: The edge_id of this BaseEdge.  # noqa: E501
        :type edge_id: str
        :param time_stamp: The time_stamp of this BaseEdge.  # noqa: E501
        :type time_stamp: str
        :param provider_name: The provider_name of this BaseEdge.  # noqa: E501
        :type provider_name: str
        :param enrichment_name: The enrichment_name of this BaseEdge.  # noqa: E501
        :type enrichment_name: str
        :param distance_name: The distance_name of this BaseEdge.  # noqa: E501
        :type distance_name: str
        :param version: The version of this BaseEdge.  # noqa: E501
        :type version: str
        :param distance: The distance of this BaseEdge.  # noqa: E501
        :type distance: float
        :param edge_type: The edge_type of this BaseEdge.  # noqa: E501
        :type edge_type: str
        """
        self.swagger_types = {
            'edge_id': str,
            'time_stamp': str,
            'provider_name': str,
            'enrichment_name': str,
            'distance_name': str,
            'version': str,
            'distance': float,
            'edge_type': str
        }

        self.attribute_map = {
            'edge_id': 'edgeId',
            'time_stamp': 'timeStamp',
            'provider_name': 'providerName',
            'enrichment_name': 'enrichmentName',
            'distance_name': 'distanceName',
            'version': 'version',
            'distance': 'distance',
            'edge_type': 'edgeType'
        }
        self._edge_id = edge_id
        self._time_stamp = time_stamp
        self._provider_name = provider_name
        self._enrichment_name = enrichment_name
        self._distance_name = distance_name
        self._version = version
        self._distance = distance
        self._edge_type = edge_type

    @classmethod
    def from_dict(cls, dikt) -> 'BaseEdge':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseEdge of this BaseEdge.  # noqa: E501
        :rtype: BaseEdge
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edge_id(self) -> str:
        """Gets the edge_id of this BaseEdge.


        :return: The edge_id of this BaseEdge.
        :rtype: str
        """
        return self._edge_id

    @edge_id.setter
    def edge_id(self, edge_id: str):
        """Sets the edge_id of this BaseEdge.


        :param edge_id: The edge_id of this BaseEdge.
        :type edge_id: str
        """

        self._edge_id = edge_id

    @property
    def time_stamp(self) -> str:
        """Gets the time_stamp of this BaseEdge.


        :return: The time_stamp of this BaseEdge.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: str):
        """Sets the time_stamp of this BaseEdge.


        :param time_stamp: The time_stamp of this BaseEdge.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp

    @property
    def provider_name(self) -> str:
        """Gets the provider_name of this BaseEdge.

        The team who builds this graph.  # noqa: E501

        :return: The provider_name of this BaseEdge.
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name: str):
        """Sets the provider_name of this BaseEdge.

        The team who builds this graph.  # noqa: E501

        :param provider_name: The provider_name of this BaseEdge.
        :type provider_name: str
        """

        self._provider_name = provider_name

    @property
    def enrichment_name(self) -> str:
        """Gets the enrichment_name of this BaseEdge.

        The type of enrichment used to construct the graph.  # noqa: E501

        :return: The enrichment_name of this BaseEdge.
        :rtype: str
        """
        return self._enrichment_name

    @enrichment_name.setter
    def enrichment_name(self, enrichment_name: str):
        """Sets the enrichment_name of this BaseEdge.

        The type of enrichment used to construct the graph.  # noqa: E501

        :param enrichment_name: The enrichment_name of this BaseEdge.
        :type enrichment_name: str
        """

        self._enrichment_name = enrichment_name

    @property
    def distance_name(self) -> str:
        """Gets the distance_name of this BaseEdge.

        The type of distance used to contruct the graph edges.  # noqa: E501

        :return: The distance_name of this BaseEdge.
        :rtype: str
        """
        return self._distance_name

    @distance_name.setter
    def distance_name(self, distance_name: str):
        """Sets the distance_name of this BaseEdge.

        The type of distance used to contruct the graph edges.  # noqa: E501

        :param distance_name: The distance_name of this BaseEdge.
        :type distance_name: str
        """

        self._distance_name = distance_name

    @property
    def version(self) -> str:
        """Gets the version of this BaseEdge.

        The version ID within the same (providerName, enrichmentName, distanceName)  # noqa: E501

        :return: The version of this BaseEdge.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this BaseEdge.

        The version ID within the same (providerName, enrichmentName, distanceName)  # noqa: E501

        :param version: The version of this BaseEdge.
        :type version: str
        """

        self._version = version

    @property
    def distance(self) -> float:
        """Gets the distance of this BaseEdge.


        :return: The distance of this BaseEdge.
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance: float):
        """Sets the distance of this BaseEdge.


        :param distance: The distance of this BaseEdge.
        :type distance: float
        """

        self._distance = distance

    @property
    def edge_type(self) -> str:
        """Gets the edge_type of this BaseEdge.

        For discriminator  # noqa: E501

        :return: The edge_type of this BaseEdge.
        :rtype: str
        """
        return self._edge_type

    @edge_type.setter
    def edge_type(self, edge_type: str):
        """Sets the edge_type of this BaseEdge.

        For discriminator  # noqa: E501

        :param edge_type: The edge_type of this BaseEdge.
        :type edge_type: str
        """
        allowed_values = ["MessageToMessageEdge", "ActorToActorEdge", "ActorToMessageEdge", "MessageToActorEdge"]  # noqa: E501
        if edge_type not in allowed_values:
            raise ValueError(
                "Invalid value for `edge_type` ({0}), must be one of {1}"
                .format(edge_type, allowed_values)
            )

        self._edge_type = edge_type
