# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from uiuc_incas_server.models.base_message_enrichment_meta import BaseMessageEnrichmentMeta  # noqa: F401,E501

class CategoryMessageEnrichmentMeta(BaseMessageEnrichmentMeta):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'categories': 'list[str]'
    }
    if hasattr(BaseMessageEnrichmentMeta, "swagger_types"):
        swagger_types.update(BaseMessageEnrichmentMeta.swagger_types)

    attribute_map = {
        'categories': 'categories'
    }
    if hasattr(BaseMessageEnrichmentMeta, "attribute_map"):
        attribute_map.update(BaseMessageEnrichmentMeta.attribute_map)

    def __init__(self, categories=None, *args, **kwargs):  # noqa: E501
        """CategoryMessageEnrichmentMeta - a model defined in Swagger"""  # noqa: E501
        self._categories = None
        self.discriminator = None
        if categories is not None:
            self.categories = categories
        BaseMessageEnrichmentMeta.__init__(self, *args, **kwargs)

    @property
    def categories(self):
        """Gets the categories of this CategoryMessageEnrichmentMeta.  # noqa: E501


        :return: The categories of this CategoryMessageEnrichmentMeta.  # noqa: E501
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this CategoryMessageEnrichmentMeta.


        :param categories: The categories of this CategoryMessageEnrichmentMeta.  # noqa: E501
        :type: list[str]
        """

        self._categories = categories

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CategoryMessageEnrichmentMeta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CategoryMessageEnrichmentMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
