# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.7.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Message(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'id': 'str',
        'title': 'str',
        'content_text': 'str',
        'author_actor': 'Actor',
        'media_type': 'str',
        'media_type_attributes': 'OneOfMediaTypeAttributes',
        'time_published': 'int',
        'geolocation': 'GeoLocation',
        'language': 'str',
        'embedded_urls': 'list[str]',
        'image_urls': 'list[str]',
        'data_tags': 'list[str]',
        'annotations': 'list[Annotation]',
        'extra_attributes': 'list[ExtraAttribute]'
    }

    attribute_map = {
        'name': 'name',
        'id': 'id',
        'title': 'title',
        'content_text': 'contentText',
        'author_actor': 'authorActor',
        'media_type': 'mediaType',
        'media_type_attributes': 'mediaTypeAttributes',
        'time_published': 'timePublished',
        'geolocation': 'geolocation',
        'language': 'language',
        'embedded_urls': 'embeddedUrls',
        'image_urls': 'imageUrls',
        'data_tags': 'dataTags',
        'annotations': 'annotations',
        'extra_attributes': 'extraAttributes'
    }

    def __init__(self, name=None, id=None, title=None, content_text=None, author_actor=None, media_type=None, media_type_attributes=None, time_published=None, geolocation=None, language=None, embedded_urls=None, image_urls=None, data_tags=None, annotations=None, extra_attributes=None):  # noqa: E501
        """Message - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._id = None
        self._title = None
        self._content_text = None
        self._author_actor = None
        self._media_type = None
        self._media_type_attributes = None
        self._time_published = None
        self._geolocation = None
        self._language = None
        self._embedded_urls = None
        self._image_urls = None
        self._data_tags = None
        self._annotations = None
        self._extra_attributes = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if content_text is not None:
            self.content_text = content_text
        if author_actor is not None:
            self.author_actor = author_actor
        if media_type is not None:
            self.media_type = media_type
        if media_type_attributes is not None:
            self.media_type_attributes = media_type_attributes
        if time_published is not None:
            self.time_published = time_published
        if geolocation is not None:
            self.geolocation = geolocation
        if language is not None:
            self.language = language
        if embedded_urls is not None:
            self.embedded_urls = embedded_urls
        if image_urls is not None:
            self.image_urls = image_urls
        if data_tags is not None:
            self.data_tags = data_tags
        if annotations is not None:
            self.annotations = annotations
        if extra_attributes is not None:
            self.extra_attributes = extra_attributes

    @property
    def name(self):
        """Gets the name of this Message.  # noqa: E501


        :return: The name of this Message.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Message.


        :param name: The name of this Message.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this Message.  # noqa: E501


        :return: The id of this Message.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Message.


        :param id: The id of this Message.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this Message.  # noqa: E501


        :return: The title of this Message.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Message.


        :param title: The title of this Message.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def content_text(self):
        """Gets the content_text of this Message.  # noqa: E501


        :return: The content_text of this Message.  # noqa: E501
        :rtype: str
        """
        return self._content_text

    @content_text.setter
    def content_text(self, content_text):
        """Sets the content_text of this Message.


        :param content_text: The content_text of this Message.  # noqa: E501
        :type: str
        """

        self._content_text = content_text

    @property
    def author_actor(self):
        """Gets the author_actor of this Message.  # noqa: E501


        :return: The author_actor of this Message.  # noqa: E501
        :rtype: Actor
        """
        return self._author_actor

    @author_actor.setter
    def author_actor(self, author_actor):
        """Sets the author_actor of this Message.


        :param author_actor: The author_actor of this Message.  # noqa: E501
        :type: Actor
        """

        self._author_actor = author_actor

    @property
    def media_type(self):
        """Gets the media_type of this Message.  # noqa: E501


        :return: The media_type of this Message.  # noqa: E501
        :rtype: str
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this Message.


        :param media_type: The media_type of this Message.  # noqa: E501
        :type: str
        """
        allowed_values = ["MEDIA_UNSPECIFIED", "News", "Reddit", "Twitter", "Webpage"]  # noqa: E501
        if media_type not in allowed_values:
            raise ValueError(
                "Invalid value for `media_type` ({0}), must be one of {1}"  # noqa: E501
                .format(media_type, allowed_values)
            )

        self._media_type = media_type

    @property
    def media_type_attributes(self):
        """Gets the media_type_attributes of this Message.  # noqa: E501


        :return: The media_type_attributes of this Message.  # noqa: E501
        :rtype: OneOfMediaTypeAttributes
        """
        return self._media_type_attributes

    @media_type_attributes.setter
    def media_type_attributes(self, media_type_attributes):
        """Sets the media_type_attributes of this Message.


        :param media_type_attributes: The media_type_attributes of this Message.  # noqa: E501
        :type: OneOfMediaTypeAttributes
        """

        self._media_type_attributes = media_type_attributes

    @property
    def time_published(self):
        """Gets the time_published of this Message.  # noqa: E501


        :return: The time_published of this Message.  # noqa: E501
        :rtype: int
        """
        return self._time_published

    @time_published.setter
    def time_published(self, time_published):
        """Sets the time_published of this Message.


        :param time_published: The time_published of this Message.  # noqa: E501
        :type: int
        """

        self._time_published = time_published

    @property
    def geolocation(self):
        """Gets the geolocation of this Message.  # noqa: E501


        :return: The geolocation of this Message.  # noqa: E501
        :rtype: GeoLocation
        """
        return self._geolocation

    @geolocation.setter
    def geolocation(self, geolocation):
        """Sets the geolocation of this Message.


        :param geolocation: The geolocation of this Message.  # noqa: E501
        :type: GeoLocation
        """

        self._geolocation = geolocation

    @property
    def language(self):
        """Gets the language of this Message.  # noqa: E501


        :return: The language of this Message.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this Message.


        :param language: The language of this Message.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def embedded_urls(self):
        """Gets the embedded_urls of this Message.  # noqa: E501


        :return: The embedded_urls of this Message.  # noqa: E501
        :rtype: list[str]
        """
        return self._embedded_urls

    @embedded_urls.setter
    def embedded_urls(self, embedded_urls):
        """Sets the embedded_urls of this Message.


        :param embedded_urls: The embedded_urls of this Message.  # noqa: E501
        :type: list[str]
        """

        self._embedded_urls = embedded_urls

    @property
    def image_urls(self):
        """Gets the image_urls of this Message.  # noqa: E501


        :return: The image_urls of this Message.  # noqa: E501
        :rtype: list[str]
        """
        return self._image_urls

    @image_urls.setter
    def image_urls(self, image_urls):
        """Sets the image_urls of this Message.


        :param image_urls: The image_urls of this Message.  # noqa: E501
        :type: list[str]
        """

        self._image_urls = image_urls

    @property
    def data_tags(self):
        """Gets the data_tags of this Message.  # noqa: E501


        :return: The data_tags of this Message.  # noqa: E501
        :rtype: list[str]
        """
        return self._data_tags

    @data_tags.setter
    def data_tags(self, data_tags):
        """Sets the data_tags of this Message.


        :param data_tags: The data_tags of this Message.  # noqa: E501
        :type: list[str]
        """

        self._data_tags = data_tags

    @property
    def annotations(self):
        """Gets the annotations of this Message.  # noqa: E501


        :return: The annotations of this Message.  # noqa: E501
        :rtype: list[Annotation]
        """
        return self._annotations

    @annotations.setter
    def annotations(self, annotations):
        """Sets the annotations of this Message.


        :param annotations: The annotations of this Message.  # noqa: E501
        :type: list[Annotation]
        """

        self._annotations = annotations

    @property
    def extra_attributes(self):
        """Gets the extra_attributes of this Message.  # noqa: E501


        :return: The extra_attributes of this Message.  # noqa: E501
        :rtype: list[ExtraAttribute]
        """
        return self._extra_attributes

    @extra_attributes.setter
    def extra_attributes(self, extra_attributes):
        """Sets the extra_attributes of this Message.


        :param extra_attributes: The extra_attributes of this Message.  # noqa: E501
        :type: list[ExtraAttribute]
        """

        self._extra_attributes = extra_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Message, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Message):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
