# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uiuc_incas_server.models.base_model_ import Model
from uiuc_incas_server.models.base_edge import BaseEdge  # noqa: F401,E501
from uiuc_incas_server import util


class MessageToActorEdge(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, edge_id: str=None, time_stamp: str=None, provider_name: str=None, enrichment_name: str=None, distance_name: str=None, version: str=None, distance: float=None, edge_type: str=None, message_id: str=None, actor_id: str=None, action_type: str=None):  # noqa: E501
        """MessageToActorEdge - a model defined in Swagger

        :param edge_id: The edge_id of this MessageToActorEdge.  # noqa: E501
        :type edge_id: str
        :param time_stamp: The time_stamp of this MessageToActorEdge.  # noqa: E501
        :type time_stamp: str
        :param provider_name: The provider_name of this MessageToActorEdge.  # noqa: E501
        :type provider_name: str
        :param enrichment_name: The enrichment_name of this MessageToActorEdge.  # noqa: E501
        :type enrichment_name: str
        :param distance_name: The distance_name of this MessageToActorEdge.  # noqa: E501
        :type distance_name: str
        :param version: The version of this MessageToActorEdge.  # noqa: E501
        :type version: str
        :param distance: The distance of this MessageToActorEdge.  # noqa: E501
        :type distance: float
        :param edge_type: The edge_type of this MessageToActorEdge.  # noqa: E501
        :type edge_type: str
        :param message_id: The message_id of this MessageToActorEdge.  # noqa: E501
        :type message_id: str
        :param actor_id: The actor_id of this MessageToActorEdge.  # noqa: E501
        :type actor_id: str
        :param action_type: The action_type of this MessageToActorEdge.  # noqa: E501
        :type action_type: str
        """
        self.swagger_types = {
            'edge_id': str,
            'time_stamp': str,
            'provider_name': str,
            'enrichment_name': str,
            'distance_name': str,
            'version': str,
            'distance': float,
            'edge_type': str,
            'message_id': str,
            'actor_id': str,
            'action_type': str
        }

        self.attribute_map = {
            'edge_id': 'edgeId',
            'time_stamp': 'timeStamp',
            'provider_name': 'providerName',
            'enrichment_name': 'enrichmentName',
            'distance_name': 'distanceName',
            'version': 'version',
            'distance': 'distance',
            'edge_type': 'edgeType',
            'message_id': 'messageId',
            'actor_id': 'actorId',
            'action_type': 'actionType'
        }
        self._edge_id = edge_id
        self._time_stamp = time_stamp
        self._provider_name = provider_name
        self._enrichment_name = enrichment_name
        self._distance_name = distance_name
        self._version = version
        self._distance = distance
        self._edge_type = edge_type
        self._message_id = message_id
        self._actor_id = actor_id
        self._action_type = action_type

    @classmethod
    def from_dict(cls, dikt) -> 'MessageToActorEdge':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MessageToActorEdge of this MessageToActorEdge.  # noqa: E501
        :rtype: MessageToActorEdge
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edge_id(self) -> str:
        """Gets the edge_id of this MessageToActorEdge.


        :return: The edge_id of this MessageToActorEdge.
        :rtype: str
        """
        return self._edge_id

    @edge_id.setter
    def edge_id(self, edge_id: str):
        """Sets the edge_id of this MessageToActorEdge.


        :param edge_id: The edge_id of this MessageToActorEdge.
        :type edge_id: str
        """

        self._edge_id = edge_id

    @property
    def time_stamp(self) -> str:
        """Gets the time_stamp of this MessageToActorEdge.


        :return: The time_stamp of this MessageToActorEdge.
        :rtype: str
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: str):
        """Sets the time_stamp of this MessageToActorEdge.


        :param time_stamp: The time_stamp of this MessageToActorEdge.
        :type time_stamp: str
        """

        self._time_stamp = time_stamp

    @property
    def provider_name(self) -> str:
        """Gets the provider_name of this MessageToActorEdge.

        The team who builds this graph.  # noqa: E501

        :return: The provider_name of this MessageToActorEdge.
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name: str):
        """Sets the provider_name of this MessageToActorEdge.

        The team who builds this graph.  # noqa: E501

        :param provider_name: The provider_name of this MessageToActorEdge.
        :type provider_name: str
        """

        self._provider_name = provider_name

    @property
    def enrichment_name(self) -> str:
        """Gets the enrichment_name of this MessageToActorEdge.

        The type of enrichment used to construct the graph.  # noqa: E501

        :return: The enrichment_name of this MessageToActorEdge.
        :rtype: str
        """
        return self._enrichment_name

    @enrichment_name.setter
    def enrichment_name(self, enrichment_name: str):
        """Sets the enrichment_name of this MessageToActorEdge.

        The type of enrichment used to construct the graph.  # noqa: E501

        :param enrichment_name: The enrichment_name of this MessageToActorEdge.
        :type enrichment_name: str
        """

        self._enrichment_name = enrichment_name

    @property
    def distance_name(self) -> str:
        """Gets the distance_name of this MessageToActorEdge.

        The type of distance used to contruct the graph edges.  # noqa: E501

        :return: The distance_name of this MessageToActorEdge.
        :rtype: str
        """
        return self._distance_name

    @distance_name.setter
    def distance_name(self, distance_name: str):
        """Sets the distance_name of this MessageToActorEdge.

        The type of distance used to contruct the graph edges.  # noqa: E501

        :param distance_name: The distance_name of this MessageToActorEdge.
        :type distance_name: str
        """

        self._distance_name = distance_name

    @property
    def version(self) -> str:
        """Gets the version of this MessageToActorEdge.

        The version ID within the same (providerName, enrichmentName, distanceName)  # noqa: E501

        :return: The version of this MessageToActorEdge.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this MessageToActorEdge.

        The version ID within the same (providerName, enrichmentName, distanceName)  # noqa: E501

        :param version: The version of this MessageToActorEdge.
        :type version: str
        """

        self._version = version

    @property
    def distance(self) -> float:
        """Gets the distance of this MessageToActorEdge.


        :return: The distance of this MessageToActorEdge.
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance: float):
        """Sets the distance of this MessageToActorEdge.


        :param distance: The distance of this MessageToActorEdge.
        :type distance: float
        """

        self._distance = distance

    @property
    def edge_type(self) -> str:
        """Gets the edge_type of this MessageToActorEdge.

        For discriminator  # noqa: E501

        :return: The edge_type of this MessageToActorEdge.
        :rtype: str
        """
        return self._edge_type

    @edge_type.setter
    def edge_type(self, edge_type: str):
        """Sets the edge_type of this MessageToActorEdge.

        For discriminator  # noqa: E501

        :param edge_type: The edge_type of this MessageToActorEdge.
        :type edge_type: str
        """
        allowed_values = ["MessageToMessageEdge", "ActorToActorEdge", "ActorToMessageEdge", "MessageToActorEdge"]  # noqa: E501
        if edge_type not in allowed_values:
            raise ValueError(
                "Invalid value for `edge_type` ({0}), must be one of {1}"
                .format(edge_type, allowed_values)
            )

        self._edge_type = edge_type

    @property
    def message_id(self) -> str:
        """Gets the message_id of this MessageToActorEdge.


        :return: The message_id of this MessageToActorEdge.
        :rtype: str
        """
        return self._message_id

    @message_id.setter
    def message_id(self, message_id: str):
        """Sets the message_id of this MessageToActorEdge.


        :param message_id: The message_id of this MessageToActorEdge.
        :type message_id: str
        """

        self._message_id = message_id

    @property
    def actor_id(self) -> str:
        """Gets the actor_id of this MessageToActorEdge.


        :return: The actor_id of this MessageToActorEdge.
        :rtype: str
        """
        return self._actor_id

    @actor_id.setter
    def actor_id(self, actor_id: str):
        """Sets the actor_id of this MessageToActorEdge.


        :param actor_id: The actor_id of this MessageToActorEdge.
        :type actor_id: str
        """

        self._actor_id = actor_id

    @property
    def action_type(self) -> str:
        """Gets the action_type of this MessageToActorEdge.


        :return: The action_type of this MessageToActorEdge.
        :rtype: str
        """
        return self._action_type

    @action_type.setter
    def action_type(self, action_type: str):
        """Sets the action_type of this MessageToActorEdge.


        :param action_type: The action_type of this MessageToActorEdge.
        :type action_type: str
        """

        self._action_type = action_type
