# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.7.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from uiuc_incas_server.models.base_enrichment import BaseEnrichment  # noqa: F401,E501

class ObjectEnrichment(BaseEnrichment):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'serialized_value': 'str'
    }
    if hasattr(BaseEnrichment, "swagger_types"):
        swagger_types.update(BaseEnrichment.swagger_types)

    attribute_map = {
        'serialized_value': 'serializedValue'
    }
    if hasattr(BaseEnrichment, "attribute_map"):
        attribute_map.update(BaseEnrichment.attribute_map)

    def __init__(self, serialized_value=None, *args, **kwargs):  # noqa: E501
        """ObjectEnrichment - a model defined in Swagger"""  # noqa: E501
        self._serialized_value = None
        self.discriminator = None
        if serialized_value is not None:
            self.serialized_value = serialized_value
        BaseEnrichment.__init__(self, *args, **kwargs)

    @property
    def serialized_value(self):
        """Gets the serialized_value of this ObjectEnrichment.  # noqa: E501


        :return: The serialized_value of this ObjectEnrichment.  # noqa: E501
        :rtype: str
        """
        return self._serialized_value

    @serialized_value.setter
    def serialized_value(self, serialized_value):
        """Sets the serialized_value of this ObjectEnrichment.


        :param serialized_value: The serialized_value of this ObjectEnrichment.  # noqa: E501
        :type: str
        """

        self._serialized_value = serialized_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ObjectEnrichment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectEnrichment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
