# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uiuc_incas_server.models.base_model_ import Model
from uiuc_incas_server import util


class Offset(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, begin: int=None, end: int=None):  # noqa: E501
        """Offset - a model defined in Swagger

        :param begin: The begin of this Offset.  # noqa: E501
        :type begin: int
        :param end: The end of this Offset.  # noqa: E501
        :type end: int
        """
        self.swagger_types = {
            'begin': int,
            'end': int
        }

        self.attribute_map = {
            'begin': 'begin',
            'end': 'end'
        }
        self._begin = begin
        self._end = end

    @classmethod
    def from_dict(cls, dikt) -> 'Offset':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Offset of this Offset.  # noqa: E501
        :rtype: Offset
        """
        return util.deserialize_model(dikt, cls)

    @property
    def begin(self) -> int:
        """Gets the begin of this Offset.


        :return: The begin of this Offset.
        :rtype: int
        """
        return self._begin

    @begin.setter
    def begin(self, begin: int):
        """Sets the begin of this Offset.


        :param begin: The begin of this Offset.
        :type begin: int
        """

        self._begin = begin

    @property
    def end(self) -> int:
        """Gets the end of this Offset.


        :return: The end of this Offset.
        :rtype: int
        """
        return self._end

    @end.setter
    def end(self, end: int):
        """Sets the end of this Offset.


        :param end: The end of this Offset.
        :type end: int
        """

        self._end = end
