# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from uiuc_incas_server.models.base_model_ import Model
from uiuc_incas_server import util


class OneOfActorMessageEdge(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """OneOfActorMessageEdge - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OneOfActorMessageEdge':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OneOfActorMessageEdge of this OneOfActorMessageEdge.  # noqa: E501
        :rtype: OneOfActorMessageEdge
        """
        return util.deserialize_model(dikt, cls)
