# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.7.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OneOfMediaTypeAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reddit_data': 'RedditData',
        'twitter_data': 'TwitterData'
    }

    attribute_map = {
        'reddit_data': 'redditData',
        'twitter_data': 'twitterData'
    }

    def __init__(self, reddit_data=None, twitter_data=None):  # noqa: E501
        """OneOfMediaTypeAttributes - a model defined in Swagger"""  # noqa: E501
        self._reddit_data = None
        self._twitter_data = None
        self.discriminator = None
        if reddit_data is not None:
            self.reddit_data = reddit_data
        if twitter_data is not None:
            self.twitter_data = twitter_data

    @property
    def reddit_data(self):
        """Gets the reddit_data of this OneOfMediaTypeAttributes.  # noqa: E501


        :return: The reddit_data of this OneOfMediaTypeAttributes.  # noqa: E501
        :rtype: RedditData
        """
        return self._reddit_data

    @reddit_data.setter
    def reddit_data(self, reddit_data):
        """Sets the reddit_data of this OneOfMediaTypeAttributes.


        :param reddit_data: The reddit_data of this OneOfMediaTypeAttributes.  # noqa: E501
        :type: RedditData
        """

        self._reddit_data = reddit_data

    @property
    def twitter_data(self):
        """Gets the twitter_data of this OneOfMediaTypeAttributes.  # noqa: E501


        :return: The twitter_data of this OneOfMediaTypeAttributes.  # noqa: E501
        :rtype: TwitterData
        """
        return self._twitter_data

    @twitter_data.setter
    def twitter_data(self, twitter_data):
        """Sets the twitter_data of this OneOfMediaTypeAttributes.


        :param twitter_data: The twitter_data of this OneOfMediaTypeAttributes.  # noqa: E501
        :type: TwitterData
        """

        self._twitter_data = twitter_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OneOfMediaTypeAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OneOfMediaTypeAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
