# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.7.  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TwitterData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'like_count': 'int',
        'retweet_count': 'int',
        'twitter_author_screenname': 'str',
        'tweet_id': 'str',
        'twitter_user_id': 'str',
        'following_count': 'int',
        'follower_count': 'int',
        'engagement_type': 'str',
        'engagement_parent_id': 'str',
        'mentioned_users': 'list[str]'
    }

    attribute_map = {
        'like_count': 'likeCount',
        'retweet_count': 'retweetCount',
        'twitter_author_screenname': 'twitterAuthorScreenname',
        'tweet_id': 'tweetId',
        'twitter_user_id': 'twitterUserId',
        'following_count': 'followingCount',
        'follower_count': 'followerCount',
        'engagement_type': 'engagementType',
        'engagement_parent_id': 'engagementParentId',
        'mentioned_users': 'mentionedUsers'
    }

    def __init__(self, like_count=None, retweet_count=None, twitter_author_screenname=None, tweet_id=None, twitter_user_id=None, following_count=None, follower_count=None, engagement_type=None, engagement_parent_id=None, mentioned_users=None):  # noqa: E501
        """TwitterData - a model defined in Swagger"""  # noqa: E501
        self._like_count = None
        self._retweet_count = None
        self._twitter_author_screenname = None
        self._tweet_id = None
        self._twitter_user_id = None
        self._following_count = None
        self._follower_count = None
        self._engagement_type = None
        self._engagement_parent_id = None
        self._mentioned_users = None
        self.discriminator = None
        if like_count is not None:
            self.like_count = like_count
        if retweet_count is not None:
            self.retweet_count = retweet_count
        if twitter_author_screenname is not None:
            self.twitter_author_screenname = twitter_author_screenname
        if tweet_id is not None:
            self.tweet_id = tweet_id
        if twitter_user_id is not None:
            self.twitter_user_id = twitter_user_id
        if following_count is not None:
            self.following_count = following_count
        if follower_count is not None:
            self.follower_count = follower_count
        if engagement_type is not None:
            self.engagement_type = engagement_type
        if engagement_parent_id is not None:
            self.engagement_parent_id = engagement_parent_id
        if mentioned_users is not None:
            self.mentioned_users = mentioned_users

    @property
    def like_count(self):
        """Gets the like_count of this TwitterData.  # noqa: E501


        :return: The like_count of this TwitterData.  # noqa: E501
        :rtype: int
        """
        return self._like_count

    @like_count.setter
    def like_count(self, like_count):
        """Sets the like_count of this TwitterData.


        :param like_count: The like_count of this TwitterData.  # noqa: E501
        :type: int
        """

        self._like_count = like_count

    @property
    def retweet_count(self):
        """Gets the retweet_count of this TwitterData.  # noqa: E501


        :return: The retweet_count of this TwitterData.  # noqa: E501
        :rtype: int
        """
        return self._retweet_count

    @retweet_count.setter
    def retweet_count(self, retweet_count):
        """Sets the retweet_count of this TwitterData.


        :param retweet_count: The retweet_count of this TwitterData.  # noqa: E501
        :type: int
        """

        self._retweet_count = retweet_count

    @property
    def twitter_author_screenname(self):
        """Gets the twitter_author_screenname of this TwitterData.  # noqa: E501


        :return: The twitter_author_screenname of this TwitterData.  # noqa: E501
        :rtype: str
        """
        return self._twitter_author_screenname

    @twitter_author_screenname.setter
    def twitter_author_screenname(self, twitter_author_screenname):
        """Sets the twitter_author_screenname of this TwitterData.


        :param twitter_author_screenname: The twitter_author_screenname of this TwitterData.  # noqa: E501
        :type: str
        """

        self._twitter_author_screenname = twitter_author_screenname

    @property
    def tweet_id(self):
        """Gets the tweet_id of this TwitterData.  # noqa: E501


        :return: The tweet_id of this TwitterData.  # noqa: E501
        :rtype: str
        """
        return self._tweet_id

    @tweet_id.setter
    def tweet_id(self, tweet_id):
        """Sets the tweet_id of this TwitterData.


        :param tweet_id: The tweet_id of this TwitterData.  # noqa: E501
        :type: str
        """

        self._tweet_id = tweet_id

    @property
    def twitter_user_id(self):
        """Gets the twitter_user_id of this TwitterData.  # noqa: E501


        :return: The twitter_user_id of this TwitterData.  # noqa: E501
        :rtype: str
        """
        return self._twitter_user_id

    @twitter_user_id.setter
    def twitter_user_id(self, twitter_user_id):
        """Sets the twitter_user_id of this TwitterData.


        :param twitter_user_id: The twitter_user_id of this TwitterData.  # noqa: E501
        :type: str
        """

        self._twitter_user_id = twitter_user_id

    @property
    def following_count(self):
        """Gets the following_count of this TwitterData.  # noqa: E501


        :return: The following_count of this TwitterData.  # noqa: E501
        :rtype: int
        """
        return self._following_count

    @following_count.setter
    def following_count(self, following_count):
        """Sets the following_count of this TwitterData.


        :param following_count: The following_count of this TwitterData.  # noqa: E501
        :type: int
        """

        self._following_count = following_count

    @property
    def follower_count(self):
        """Gets the follower_count of this TwitterData.  # noqa: E501


        :return: The follower_count of this TwitterData.  # noqa: E501
        :rtype: int
        """
        return self._follower_count

    @follower_count.setter
    def follower_count(self, follower_count):
        """Sets the follower_count of this TwitterData.


        :param follower_count: The follower_count of this TwitterData.  # noqa: E501
        :type: int
        """

        self._follower_count = follower_count

    @property
    def engagement_type(self):
        """Gets the engagement_type of this TwitterData.  # noqa: E501


        :return: The engagement_type of this TwitterData.  # noqa: E501
        :rtype: str
        """
        return self._engagement_type

    @engagement_type.setter
    def engagement_type(self, engagement_type):
        """Sets the engagement_type of this TwitterData.


        :param engagement_type: The engagement_type of this TwitterData.  # noqa: E501
        :type: str
        """
        allowed_values = ["ENGAGEMENT_UNSPECIFIED", "mention", "quote", "reply", "retweet", "tweet", "page_post"]  # noqa: E501
        if engagement_type not in allowed_values:
            raise ValueError(
                "Invalid value for `engagement_type` ({0}), must be one of {1}"  # noqa: E501
                .format(engagement_type, allowed_values)
            )

        self._engagement_type = engagement_type

    @property
    def engagement_parent_id(self):
        """Gets the engagement_parent_id of this TwitterData.  # noqa: E501


        :return: The engagement_parent_id of this TwitterData.  # noqa: E501
        :rtype: str
        """
        return self._engagement_parent_id

    @engagement_parent_id.setter
    def engagement_parent_id(self, engagement_parent_id):
        """Sets the engagement_parent_id of this TwitterData.


        :param engagement_parent_id: The engagement_parent_id of this TwitterData.  # noqa: E501
        :type: str
        """

        self._engagement_parent_id = engagement_parent_id

    @property
    def mentioned_users(self):
        """Gets the mentioned_users of this TwitterData.  # noqa: E501


        :return: The mentioned_users of this TwitterData.  # noqa: E501
        :rtype: list[str]
        """
        return self._mentioned_users

    @mentioned_users.setter
    def mentioned_users(self, mentioned_users):
        """Sets the mentioned_users of this TwitterData.


        :param mentioned_users: The mentioned_users of this TwitterData.  # noqa: E501
        :type: list[str]
        """

        self._mentioned_users = mentioned_users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TwitterData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TwitterData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
