# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UiucSegment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'referenced_actor_uuid': 'list[str]',
        'extra_attributes': 'ExtraAttributes'
    }

    attribute_map = {
        'uuid': 'uuid',
        'referenced_actor_uuid': 'referencedActorUuid',
        'extra_attributes': 'extraAttributes'
    }

    def __init__(self, uuid=None, referenced_actor_uuid=None, extra_attributes=None):  # noqa: E501
        """UiucSegment - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._referenced_actor_uuid = None
        self._extra_attributes = None
        self.discriminator = None
        self.uuid = uuid
        if referenced_actor_uuid is not None:
            self.referenced_actor_uuid = referenced_actor_uuid
        if extra_attributes is not None:
            self.extra_attributes = extra_attributes

    @property
    def uuid(self):
        """Gets the uuid of this UiucSegment.  # noqa: E501

        The unique segment identifier  # noqa: E501

        :return: The uuid of this UiucSegment.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this UiucSegment.

        The unique segment identifier  # noqa: E501

        :param uuid: The uuid of this UiucSegment.  # noqa: E501
        :type: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def referenced_actor_uuid(self):
        """Gets the referenced_actor_uuid of this UiucSegment.  # noqa: E501


        :return: The referenced_actor_uuid of this UiucSegment.  # noqa: E501
        :rtype: list[str]
        """
        return self._referenced_actor_uuid

    @referenced_actor_uuid.setter
    def referenced_actor_uuid(self, referenced_actor_uuid):
        """Sets the referenced_actor_uuid of this UiucSegment.


        :param referenced_actor_uuid: The referenced_actor_uuid of this UiucSegment.  # noqa: E501
        :type: list[str]
        """

        self._referenced_actor_uuid = referenced_actor_uuid

    @property
    def extra_attributes(self):
        """Gets the extra_attributes of this UiucSegment.  # noqa: E501


        :return: The extra_attributes of this UiucSegment.  # noqa: E501
        :rtype: ExtraAttributes
        """
        return self._extra_attributes

    @extra_attributes.setter
    def extra_attributes(self, extra_attributes):
        """Sets the extra_attributes of this UiucSegment.


        :param extra_attributes: The extra_attributes of this UiucSegment.  # noqa: E501
        :type: ExtraAttributes
        """

        self._extra_attributes = extra_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UiucSegment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UiucSegment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
