# coding: utf-8

"""
    INCAS TA2-UIUC Datatypes

    This API document is defined based on INCAS Common Datatypes version 0.0.3.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UiucSegmentCollectionMeta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'collection_name': 'str',
        'provider_name': 'str',
        'version': 'str',
        'segments': 'list[str]'
    }

    attribute_map = {
        'description': 'description',
        'collection_name': 'collectionName',
        'provider_name': 'providerName',
        'version': 'version',
        'segments': 'segments'
    }

    def __init__(self, description=None, collection_name=None, provider_name=None, version=None, segments=None):  # noqa: E501
        """UiucSegmentCollectionMeta - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._collection_name = None
        self._provider_name = None
        self._version = None
        self._segments = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if collection_name is not None:
            self.collection_name = collection_name
        if provider_name is not None:
            self.provider_name = provider_name
        if version is not None:
            self.version = version
        if segments is not None:
            self.segments = segments

    @property
    def description(self):
        """Gets the description of this UiucSegmentCollectionMeta.  # noqa: E501

        Description of the segment.  # noqa: E501

        :return: The description of this UiucSegmentCollectionMeta.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UiucSegmentCollectionMeta.

        Description of the segment.  # noqa: E501

        :param description: The description of this UiucSegmentCollectionMeta.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def collection_name(self):
        """Gets the collection_name of this UiucSegmentCollectionMeta.  # noqa: E501

        Name of the segment.  # noqa: E501

        :return: The collection_name of this UiucSegmentCollectionMeta.  # noqa: E501
        :rtype: str
        """
        return self._collection_name

    @collection_name.setter
    def collection_name(self, collection_name):
        """Sets the collection_name of this UiucSegmentCollectionMeta.

        Name of the segment.  # noqa: E501

        :param collection_name: The collection_name of this UiucSegmentCollectionMeta.  # noqa: E501
        :type: str
        """

        self._collection_name = collection_name

    @property
    def provider_name(self):
        """Gets the provider_name of this UiucSegmentCollectionMeta.  # noqa: E501

        The team (e.g., UIUC-DMG) who provides the segment.  # noqa: E501

        :return: The provider_name of this UiucSegmentCollectionMeta.  # noqa: E501
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name):
        """Sets the provider_name of this UiucSegmentCollectionMeta.

        The team (e.g., UIUC-DMG) who provides the segment.  # noqa: E501

        :param provider_name: The provider_name of this UiucSegmentCollectionMeta.  # noqa: E501
        :type: str
        """

        self._provider_name = provider_name

    @property
    def version(self):
        """Gets the version of this UiucSegmentCollectionMeta.  # noqa: E501

        The version within the same (provider, name).  # noqa: E501

        :return: The version of this UiucSegmentCollectionMeta.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this UiucSegmentCollectionMeta.

        The version within the same (provider, name).  # noqa: E501

        :param version: The version of this UiucSegmentCollectionMeta.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def segments(self):
        """Gets the segments of this UiucSegmentCollectionMeta.  # noqa: E501


        :return: The segments of this UiucSegmentCollectionMeta.  # noqa: E501
        :rtype: list[str]
        """
        return self._segments

    @segments.setter
    def segments(self, segments):
        """Sets the segments of this UiucSegmentCollectionMeta.


        :param segments: The segments of this UiucSegmentCollectionMeta.  # noqa: E501
        :type: list[str]
        """

        self._segments = segments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UiucSegmentCollectionMeta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UiucSegmentCollectionMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
