# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_actor_enrichment import BaseActorEnrichment  # noqa: F401,E501
from swagger_server import util


class ArrayActorEnrichment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, actor_uuid: str=None, provider_name: str=None, enrichment_name: str=None, version: str=None, confidence: float=None, attribute_value: List[float]=None):  # noqa: E501
        """ArrayActorEnrichment - a model defined in Swagger

        :param actor_uuid: The actor_uuid of this ArrayActorEnrichment.  # noqa: E501
        :type actor_uuid: str
        :param provider_name: The provider_name of this ArrayActorEnrichment.  # noqa: E501
        :type provider_name: str
        :param enrichment_name: The enrichment_name of this ArrayActorEnrichment.  # noqa: E501
        :type enrichment_name: str
        :param version: The version of this ArrayActorEnrichment.  # noqa: E501
        :type version: str
        :param confidence: The confidence of this ArrayActorEnrichment.  # noqa: E501
        :type confidence: float
        :param attribute_value: The attribute_value of this ArrayActorEnrichment.  # noqa: E501
        :type attribute_value: List[float]
        """
        self.swagger_types = {
            'actor_uuid': str,
            'provider_name': str,
            'enrichment_name': str,
            'version': str,
            'confidence': float,
            'attribute_value': List[float]
        }

        self.attribute_map = {
            'actor_uuid': 'actorUuid',
            'provider_name': 'providerName',
            'enrichment_name': 'enrichmentName',
            'version': 'version',
            'confidence': 'confidence',
            'attribute_value': 'attributeValue'
        }
        self._actor_uuid = actor_uuid
        self._provider_name = provider_name
        self._enrichment_name = enrichment_name
        self._version = version
        self._confidence = confidence
        self._attribute_value = attribute_value

    @classmethod
    def from_dict(cls, dikt) -> 'ArrayActorEnrichment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArrayActorEnrichment of this ArrayActorEnrichment.  # noqa: E501
        :rtype: ArrayActorEnrichment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def actor_uuid(self) -> str:
        """Gets the actor_uuid of this ArrayActorEnrichment.


        :return: The actor_uuid of this ArrayActorEnrichment.
        :rtype: str
        """
        return self._actor_uuid

    @actor_uuid.setter
    def actor_uuid(self, actor_uuid: str):
        """Sets the actor_uuid of this ArrayActorEnrichment.


        :param actor_uuid: The actor_uuid of this ArrayActorEnrichment.
        :type actor_uuid: str
        """

        self._actor_uuid = actor_uuid

    @property
    def provider_name(self) -> str:
        """Gets the provider_name of this ArrayActorEnrichment.

        The team (e.g., USC) who provides the enrichment.  # noqa: E501

        :return: The provider_name of this ArrayActorEnrichment.
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name: str):
        """Sets the provider_name of this ArrayActorEnrichment.

        The team (e.g., USC) who provides the enrichment.  # noqa: E501

        :param provider_name: The provider_name of this ArrayActorEnrichment.
        :type provider_name: str
        """

        self._provider_name = provider_name

    @property
    def enrichment_name(self) -> str:
        """Gets the enrichment_name of this ArrayActorEnrichment.

        The enrichment (e.g., age, gender) name for the enrichment.  # noqa: E501

        :return: The enrichment_name of this ArrayActorEnrichment.
        :rtype: str
        """
        return self._enrichment_name

    @enrichment_name.setter
    def enrichment_name(self, enrichment_name: str):
        """Sets the enrichment_name of this ArrayActorEnrichment.

        The enrichment (e.g., age, gender) name for the enrichment.  # noqa: E501

        :param enrichment_name: The enrichment_name of this ArrayActorEnrichment.
        :type enrichment_name: str
        """

        self._enrichment_name = enrichment_name

    @property
    def version(self) -> str:
        """Gets the version of this ArrayActorEnrichment.

        The version within the same (provider, enrichmentName).  # noqa: E501

        :return: The version of this ArrayActorEnrichment.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this ArrayActorEnrichment.

        The version within the same (provider, enrichmentName).  # noqa: E501

        :param version: The version of this ArrayActorEnrichment.
        :type version: str
        """

        self._version = version

    @property
    def confidence(self) -> float:
        """Gets the confidence of this ArrayActorEnrichment.

        The confidence that this enrichment is correct, expressed as a percentage between 0.0 and 1.0  # noqa: E501

        :return: The confidence of this ArrayActorEnrichment.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence: float):
        """Sets the confidence of this ArrayActorEnrichment.

        The confidence that this enrichment is correct, expressed as a percentage between 0.0 and 1.0  # noqa: E501

        :param confidence: The confidence of this ArrayActorEnrichment.
        :type confidence: float
        """

        self._confidence = confidence

    @property
    def attribute_value(self) -> List[float]:
        """Gets the attribute_value of this ArrayActorEnrichment.


        :return: The attribute_value of this ArrayActorEnrichment.
        :rtype: List[float]
        """
        return self._attribute_value

    @attribute_value.setter
    def attribute_value(self, attribute_value: List[float]):
        """Sets the attribute_value of this ArrayActorEnrichment.


        :param attribute_value: The attribute_value of this ArrayActorEnrichment.
        :type attribute_value: List[float]
        """

        self._attribute_value = attribute_value
