# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reddit_data import RedditData  # noqa: F401,E501
from swagger_server.models.twitter_data import TwitterData  # noqa: F401,E501
from swagger_server import util


class OneOfMediaTypeAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reddit_data: RedditData=None, twitter_data: TwitterData=None):  # noqa: E501
        """OneOfMediaTypeAttributes - a model defined in Swagger

        :param reddit_data: The reddit_data of this OneOfMediaTypeAttributes.  # noqa: E501
        :type reddit_data: RedditData
        :param twitter_data: The twitter_data of this OneOfMediaTypeAttributes.  # noqa: E501
        :type twitter_data: TwitterData
        """
        self.swagger_types = {
            'reddit_data': RedditData,
            'twitter_data': TwitterData
        }

        self.attribute_map = {
            'reddit_data': 'redditData',
            'twitter_data': 'twitterData'
        }
        self._reddit_data = reddit_data
        self._twitter_data = twitter_data

    @classmethod
    def from_dict(cls, dikt) -> 'OneOfMediaTypeAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OneOfMediaTypeAttributes of this OneOfMediaTypeAttributes.  # noqa: E501
        :rtype: OneOfMediaTypeAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reddit_data(self) -> RedditData:
        """Gets the reddit_data of this OneOfMediaTypeAttributes.


        :return: The reddit_data of this OneOfMediaTypeAttributes.
        :rtype: RedditData
        """
        return self._reddit_data

    @reddit_data.setter
    def reddit_data(self, reddit_data: RedditData):
        """Sets the reddit_data of this OneOfMediaTypeAttributes.


        :param reddit_data: The reddit_data of this OneOfMediaTypeAttributes.
        :type reddit_data: RedditData
        """

        self._reddit_data = reddit_data

    @property
    def twitter_data(self) -> TwitterData:
        """Gets the twitter_data of this OneOfMediaTypeAttributes.


        :return: The twitter_data of this OneOfMediaTypeAttributes.
        :rtype: TwitterData
        """
        return self._twitter_data

    @twitter_data.setter
    def twitter_data(self, twitter_data: TwitterData):
        """Sets the twitter_data of this OneOfMediaTypeAttributes.


        :param twitter_data: The twitter_data of this OneOfMediaTypeAttributes.
        :type twitter_data: TwitterData
        """

        self._twitter_data = twitter_data
